[project]
name = "vdb-core"
version = "0.1.0"
description = "Domain layer for VectorDB - entities, value objects, and interfaces"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.10.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/vdb_core"]
