[project]
name = "vdb-core"
version = "0.1.0"
description = "Domain layer for VectorDB - entities, value objects, and interfaces"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=9.4.0",
    "asyncpg>=0.29.0",
    "cohere>=5.0.0",
    "fastapi>=0.115.0",
    "greenlet>=3.0.0",
    "httpx>=0.27.0",
    "numpy>=2.0.0",
    "pika>=1.3.0",
    "pydantic>=2.10.0",
    "pyyaml>=6.0",
    "sqlalchemy>=2.0.0",
    "temporalio>=1.6.0",
    "uvicorn[standard]>=0.32.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.0",
    "python-dotenv>=1.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/vdb_core"]

[dependency-groups]
dev = [
    "types-pika>=1.2.0b1",
    "types-pyyaml>=6.0.12.20250915",
]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false

# Suppress import errors for packages without type stubs
[[tool.mypy.overrides]]
module = [
    "asyncpg",
    "asyncpg.*",
    "vdb_core.domain.entities.library.chunk",
]
ignore_missing_imports = true
