apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-postgres-data
  namespace: vdb
  labels:
    app: temporal-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and specify storageClassName if needed
  # storageClassName: standard
