apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-postgres-data
  namespace: vdb
  labels:
    app: app-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Uncomment and specify storageClassName if needed
  # storageClassName: standard
