---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: vdb
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: vdb
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        # Wait for app-postgres to be ready
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h app-postgres -U vdbuser -d vectordb; do
                echo "Waiting for app-postgres...";
                sleep 2;
              done
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: vdb-secrets
                  key: POSTGRES_PASSWORD
        # Wait for RabbitMQ to be ready
        - name: wait-for-rabbitmq
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq...";
                sleep 2;
              done
        # Wait for Temporal to be ready
        - name: wait-for-temporal
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              until nc -z temporal 7233; do
                echo "Waiting for temporal...";
                sleep 2;
              done
      volumes:
        - name: config-volume
          configMap:
            name: vdb-app-config
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/ci-dev-376017/vdb-images/vdb-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config.yaml
              subPath: config.yaml
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vdb-secrets
                  key: DATABASE_URL
            - name: TEMPORAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: vdb-config
                  key: TEMPORAL_HOST
            - name: TEMPORAL_PORT
              valueFrom:
                configMapKeyRef:
                  name: vdb-config
                  key: TEMPORAL_PORT
            - name: TEMPORAL_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: vdb-config
                  key: TEMPORAL_NAMESPACE
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: vdb-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: vdb-config
                  key: RABBITMQ_PORT
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
